### ISSUE TITLE
Completar el README

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/charla_s3_2017#1]
- [x] Título: ¿Todos de acuerdo con el título? ¿Sugerencias?
- [ ] Descripción de la charla
- [ ] Link a la charla cuando esté completa

**Comment by astrojuanlu** [comment]
Visto que el evento va a ser de corte formal, estoy de acuerdo con el título de la charla :+1:

**Comment by AlexS12** [comment]
¿@AeroPython/s3-talk-2017, alguien se puede encargar de arreglar un poquito el README? Faltaría una pequeña descripción de la charla (con un par de líneas basta yo creo).

Yo me puedo encargar de poner el link a las diapositivas cuando junte todo
