### ISSUE TITLE
¿Qué hacemos en AeroPython? Poliastro

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/charla_s3_2017#5]
@Juanlu001, ¿puedes echarle una mano a @AunSiro con esto? Tres frases sobre poliastro y un ejemplo de esos guays con widget va que chuta yo creo, pero vosotros mandáis!

**Comment by astrojuanlu** [comment]
Tengo varias charlas en Internet sobre poliastro, por ejemplo:

* https://github.com/Juanlu001/Lightning-talk-poliastro
* http://nbviewer.jupyter.org/format/slides/github/Juanlu001/Talk-SpaceUpBCN/blob/master/Open%20Source%2C%20Hardware%20%26%20Knowledge%20for%20Space.ipynb
* https://speakerdeck.com/pybonacci/through-python-to-the-stars

Estaré ocupado preparando el OSCW pero si necesitáis ayuda me decís :)

**Comment by astrojuanlu** [comment]
Y ahora, esta:

https://github.com/poliastro/oscw2017-talk

**Comment by AunSiro** [comment]
Acabo de subir mi parrafito de poliastro!

**Comment by AlexS12** [comment]
Perfecto! Gracias Siro!
